### ISSUE TITLE
r18图片搜索

### ISSUE THREAD

**Issue by MichaelLai412** [txperl/PixivBiu#1]
大佬，我想问下目前的版本能搜索r18的图片吗？我这边的PixivBiu自动把r18的图片全过滤了，我在localhost那个用户界面里找不到能设置不过滤r18的选项，所以想问下。谢谢了。

**Comment by txperl** [comment]
可以的，但前提是你 pixiv 账号打开了 r18 选项才行。

**Comment by MichaelLai412** [comment]
> 可以的，但前提是你 pixiv 账号打开了 r18 选项才行。

好。我用了另外一个账号（已调了r18选项）登陆后发现确实是这样的，谢了。
