### ISSUE TITLE
你好，已经翻墙了，为什么打不开，求解

### ISSUE THREAD

**Issue by chiseweiyun** [txperl/PixivBiu#11]
[PixivBiu] 检测网络状态...
[PixivBiu] 由于 Pixiv 禁止了目前使用的 Login API 账号密码登陆方式，暂时只能使用 Token 进行登录
是否开始手动获取 Token 后使用? (y / n): y
[Login] 请按以下步骤进行操作:
1. 访问「https://app-api.pixiv.net/web/v1/login?code_challenge=DvjoDoznFeMyezRYKu9JAv3z47JCM6bWMrQ61AlNfFU&code_challenge_method=S256&client=pixiv-android」
（若您别无他法，还是不能访问以上网址，那可参考此方式「https://github.com/mashirozx/Pixiv-Nginx」先进行配置）
2. 打开浏览器的「开发者工具 / Dev Console / F12」，切换至「Network」标签
3. 开启「Preserve log / 持续记录」
4. 在「Filter / 筛选」文本框中输入「callback?」
5. 登录您的 Pixiv 账号
6. 成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段，将「code」后面的参数输入本程序
Code: cYE0r3ifLQE_X_0UH4ta4yKGPOa3q9P76DIIYD_4l3s
Error:
Request Error.
Response: {'has_error': True, 'errors': {'system': {'message': 'The authorization code has expired', 'code': 1508}}, 'error': 'invalid_grant'}
End;
[PixivBiu] 免代理请求失败。开始尝试代理方式，请务必确保程序可通过您的设置访问 Pixiv
[Login] 无法获取代理监听地址，是否要手动输入? (y / n): y
请输入代理监听地址:

**Comment by txperl** [comment]
错误提示为「The authorization code has expired」，表示 Code 已过期。

请在执行 1-6 步骤的时候尽量操作得快一些。
