### ISSUE TITLE
请问收藏数标签如何使用

### ISSUE THREAD

**Issue by a13864209110** [txperl/PixivBiu#13]
下方的这种标签请问改如何使用阿 可否来个搜索格式谢谢了
我使用的搜索格式为 但搜不到结果
@s=風景 -o （title 1000）

Pixiv 收藏数标签
配合收藏数标签一起使用（title 1000）体验更加。

title 100 ：搜索收藏数在 100 - 500 的内容
title 500 ：500 - 1000
title 1000 ：1000 - 5000
title 5000 ：5000 - 10000
title 10000 ：10000 - ∞

**Comment by txperl** [comment]
目前 Pixiv 好像已经不再给普通用户使用收藏数标签过滤了。

但仍然可以用，只是关键词后的标签数匹配的是作品的标签。也就是说，如果一个作品没有特地标明它有多少收藏数，那大概率也是无法搜索到的。

PixivBiu 中使用方式如下：
- さんかれあ 1000
- @s=さんかれあ 1000 -t
- （上述两种是等价的）

在你的例子中，那应该输入：「@s=風景 1000 -t」或者接「風景 1000」即可。

不建议使用「@s=... -o」的全标签搜索模式，这样的话会完全匹配作品标签名，结果可能会比较少。
