### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by qxchitu** [txperl/PixivBiu#14]
Error:
[ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
End;
Error:
Request Error.
Response: {'has_error': True, 'errors': {'system': {'message': '不正なリクエストです。', 'code': 918}}, 'error': 'invalid_request'}
End;
[PixivBiu] Pixiv 登陆失败

**Comment by txperl** [comment]
错误信息中有提示「不正なリクエストです」，使用最新版就会提示你 Code 错误。

应该是你填写的 Code 并不是按程序所指示需要的。
