### ISSUE TITLE
一定是我哪里有问题，无法登录

### ISSUE THREAD

**Issue by lzlclzyx** [txperl/PixivBiu#15]
按照提示的说明操作，但是还是无法登陆。

不知是因为我复制错误，还是因为我用的代理梯子，还是其他地方......

https://link.jscdn.cn/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBZ0hxbmpLUUpNOFVweDJiaXA3UmJFcW41YnNmP2U9MzJudlYx.png

**Comment by warm-ice0x00** [comment]
试试使用默认的 `config.yml`（重新下载解压）。另外，如果反复询问 Code，先按照说明获取并输入 Code，然后关掉程序，过一段时间再打开即可。

**Comment by warm-ice0x00** [comment]
换不同的梯子，多试几次就好了。

**Comment by txperl** [comment]
不好意思，前几天在准备考试...

错误代码提示是 Code 不正确，如果保证自己 Code 确实没错获取错误的话，那可能是网络问题。确实，PixivBiu 在登陆这一块体验不是很好，特别是在没有代理或是代理不稳定的情况下，下个版本在这方面会优化的。

所以，确保自己网络、代理访问 Pixiv 通畅，可以避免很多登陆时会出现的问题。可以试一下换不同的线路和开全局模式看看。

**Comment by txperl** [comment]
可以尝试使用新版本，其对登录功能进行了一定优化。
