### ISSUE TITLE
关于如果公开部署的问题

### ISSUE THREAD

**Issue by zzcabc** [txperl/PixivBiu#21]
`如果公开部署，请务必停用 do 类插件，以防滥用`

是在app/config/switch.yml中禁用吗

**Comment by zzcabc** [comment]
`程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号`
关于这点，我没有遇到，程序每次启动获取的Code不同，我在测试时都使用了同一个Code依旧可以登录。另外Docker镜像我使用了pyinstaller构建linux不同架构的可执行文件，缩小体积为44M

**Comment by txperl** [comment]
> 
> 
> `程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号` 关于这点，我没有遇到，程序每次启动获取的Code不同，我在测试时都使用了同一个Code依旧可以登录。另外Docker镜像我使用了pyinstaller构建linux不同架构的可执行文件，缩小体积为44M

啊，这样的吗... 不太可能啊，之后我好好测试一下。登录方式也需要完善一下。

是使用 [pixivbiu#py-pkger](https://github.com/txperl/PixivBiu/blob/831cc0fc4875a946ed31315d1d0fdb3abc3bc31b/.pkg/py-pkger.py) 打包的吗？

**Comment by zzcabc** [comment]
是的，参照pkg.yml的打包方式进行打包[我的项目的Dockerfile.test](https://github.com/zzcabc/Docker_Buildx_PixivBiu/blob/master/Dockerfile.test)
如果你想测试可以使用
```sh
docker run -d \
    --name pixivbiu \
    -p 本机端口:4001 \
    -v $PWD/config.yml:/PixivBiu/config.yml \
    -v $PWD/downloads:/PixivBiu/downloads \
    -v $PWD/.token.json:/PivixBiu/usr/.token.json \
    zzcabc/pixivbiu-test
```

**Comment by zzcabc** [comment]
实测，当无.token.json时需要登录，有.token.json时直接登录，这个token是今天上午获取的
![image](https://user-images.githubusercontent.com/46120743/139627239-f58882f9-7649-4ff4-bef4-b30f686ee33c.png)
![image](https://user-images.githubusercontent.com/46120743/139627327-0be6926d-2369-483e-98b4-12dedd74d77f.png)
![image](https://user-images.githubusercontent.com/46120743/139627352-86030708-64fd-4cfb-a852-e29c78241304.png)
![image](https://user-images.githubusercontent.com/46120743/139627379-025c752d-8dbd-481b-9d6a-9cdaeecbc18a.png)

**Comment by txperl** [comment]
> 实测，当无.token.json时需要登录，有.token.json时直接登录，这个token是今天上午获取的
> 
> ![image](https://user-images.githubusercontent.com/46120743/139627239-f58882f9-7649-4ff4-bef4-b30f686ee33c.png)
> 
> ![image](https://user-images.githubusercontent.com/46120743/139627327-0be6926d-2369-483e-98b4-12dedd74d77f.png)
> 
> ![image](https://user-images.githubusercontent.com/46120743/139627352-86030708-64fd-4cfb-a852-e29c78241304.png)
> 
> ![image](https://user-images.githubusercontent.com/46120743/139627379-025c752d-8dbd-481b-9d6a-9cdaeecbc18a.png)
> 
> 

是的，这是 token 文件就是 PixivBiu 引导你填写 Code 后保存的。

PixivBiu 的登录机制是这样的：如果有 `.token.json` 文件，则直接利用 token 文件中的信息进行登录；若无，则进入 Token 引导流程，用户获取并填写相应 Code 后，程序通过 Code 获取 token 并写入 `.token.json` 文件，然后进行登录。

**Comment by zzcabc** [comment]
而且，一个正常使用的code，应该可以持续很长时间，在之前docker测试过程中的code，目前依旧可以使用

**Comment by txperl** [comment]
> 
> 
> 而且，一个正常使用的code，应该可以持续很长时间，在之前docker测试过程中的code，目前依旧可以使用

code 是用来获取 token 的，它们是不同的...

**Comment by Kimiato** [comment]
现在这个配置项似乎已经不生效了

**Comment by txperl** [comment]
> 现在这个配置项似乎已经不生效了

请问具体是哪一个配置项？

**Comment by zzcabc** [comment]
> > 现在这个配置项似乎已经不生效了
> 
> 请问具体是哪一个配置项？

应该是那几个true的

**Comment by Kimiato** [comment]
> > 现在这个配置项似乎已经不生效了
> 
> 请问具体是哪一个配置项？

这几个配置项，在switch改了之后并不会生效了

```python
 plugin: 
   do_dl.py: true 
   do_dl_stop.py: true 
   do_follow.py: true 
   do_mark.py: true 
   do_unfollow.py: true 
   do_unmark.py: true
```

**Comment by txperl** [comment]
@Kimiato 

因为在某一版本中调整了插件代码文件命名，所以原先的配置无法生效。

如果要禁用的话，更改为如下格式即可。

```yaml
plugin:
  dl.py: false
  dl_stop.py: false
  follow.py: false
  mark.py: false
  unfollow.py: false
  unmark.py: false
```
