### ISSUE TITLE
关于无法进行正常进行 Pixiv Token 登陆，请调整后重试。

### ISSUE THREAD

**Issue by aaaihw** [txperl/PixivBiu#22]
[PixivBiu] 已启用系统代理地址: 127.0.0.1:10809
[PixivBiu] 检测网络状态...
[PixivBiu] 无法访问 Pixiv，启用 byPassSni API
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
是否开始手动获取 Token 后继续使用? (y / n): y
[Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
[Login Helper] 开始进行网络检测...
检测到内容为 127.0.0.1:10809 的代理监听地址，是否需要更改? (y / n): n
[Network Checker] https://public-api.secure.pixiv.net ❌
[Network Checker] https://1.0.0.1/dns-query ❌
[Network Checker] https://1.1.1.1/dns-query ❌
[Network Checker] https://[2606:4700:4700::1001]/dns-query ❌
[Network Checker] https://[2606:4700:4700::1111]/dns-query ❌
[Network Checker] https://cloudflare-dns.com/dns-query ❌
[PixivBiu] 您的网络无法正常进行 Pixiv Token 登陆，请调整后重试。
按任意键退出...

请问是哪里配置有问题吗？不是很懂

**Comment by zzcabc** [comment]
第一步：访问https://app-api.pixiv.net/web/v1/login?code_challenge=g0i2R7R7AvhAZBGCgIzoGjex23IOMM_szMvqzOBCpso&code_challenge_method=S256&client=pixiv-android

第二步： 打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签

第三步：开启「Preserve log / 持续记录」

第四步：在「Filter / 筛选」文本框中输入「callback?

第五步：登录您的 Pixiv 账号

第六步：成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=****************」的字段

第七步：将复制code后面*******，创建`.token.json`文件放到usr目录下，
以下是内容
```
{
          "token":"Code"
}
```
第八步：将config.yml中`isToken`改为true
重新打开软件


看端口应该是v2rayn，尝试切换成全局，如果还不行可以更换代理看看

**Comment by txperl** [comment]
> 
> 
> [PixivBiu] 已启用系统代理地址: 127.0.0.1:10809 [PixivBiu] 检测网络状态... [PixivBiu] 无法访问 Pixiv，启用 byPassSni API [PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录 是否开始手动获取 Token 后继续使用? (y / n): y [Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率 [Login Helper] 开始进行网络检测... 检测到内容为 127.0.0.1:10809 的代理监听地址，是否需要更改? (y / n): y 请输入代理监听地址(可留空): [Network Checker] https://public-api.secure.pixiv.net ❌ [Network Checker] https://1.0.0.1/dns-query ❌ [Network Checker] https://1.1.1.1/dns-query ❌ [Network Checker] https://[2606:4700:4700::1001]/dns-query ❌ [Network Checker] https://[2606:4700:4700::1111]/dns-query ❌ [Network Checker] https://cloudflare-dns.com/dns-query ❌ [PixivBiu] 您的网络无法正常进行 Pixiv Token 登陆，请调整后重试。 按任意键退出...
> 
> 本地网络无法登录请求吗？我直接点链接的话倒是能打开。。 改完了，还是一样，orz

网络问题，建议换个代理或者切个网络。

**Comment by txperl** [comment]
> 
> 
> 第一步：访问https://app-api.pixiv.net/web/v1/login?code_challenge=g0i2R7R7AvhAZBGCgIzoGjex23IOMM_szMvqzOBCpso&code_challenge_method=S256&client=pixiv-android
> 
> 第二步： 打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
> 
> 第三步：开启「Preserve log / 持续记录」
> 
> 第四步：在「Filter / 筛选」文本框中输入「callback?
> 
> 第五步：登录您的 Pixiv 账号
> 
> 第六步：成功登录后，会出现一个类似「[https://app-api.pixiv.net/.../callback?state=...&code=****************」的字段](https://app-api.pixiv.net/.../callback?state=...&code=****************%E3%80%8D%E7%9A%84%E5%AD%97%E6%AE%B5)
> 
> 第七步：将复制code后面*******，创建`.token.json`文件放到usr目录下， 以下是内容
> 
> ```
> {
>           "token":"Code"
> }
> ```
> 
> 第八步：将config.yml中`isToken`改为true 重新打开软件
> 
> 看端口应该是v2rayn，尝试切换成全局，如果还不行可以更换代理看看

第七步是程序执行的，`.token.json` 文件中的 `token` 字段不是获取到的 Code... 难道这方法也可以直接登录？！我没有尝试过。（（

第八步其实不需要的，程序已经默认强制开启了 Token 登录模式，在接下来的新版本中此配置项也会被移除。

**Comment by aaaihw** [comment]
感谢大佬们的回复，后面我再用留空的方法可以下一步了。  推测是网络的问题。

但是输入token 后 报错ssl error？
试过好几次，应该不是超时。。


### C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a>python main.py
[PixivBiu] 已启用系统代理地址: 127.0.0.1:10809
[PixivBiu] 检测网络状态...
[PixivBiu] 无法访问 Pixiv，启用 byPassSni API
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
是否开始手动获取 Token 后继续使用? (y / n): y
[Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
[Login Helper] 开始进行网络检测...
检测到内容为 127.0.0.1:10809 的代理监听地址，是否需要更改? (y / n): y
请输入代理监听地址(可留空):
[Network Checker] https://public-api.secure.pixiv.net ✔️
[Network Checker] https://1.0.0.1/dns-query ✔️
[Network Checker] https://1.1.1.1/dns-query ✔️
[Network Checker] https://[2606:4700:4700::1001]/dns-query ❌
[Network Checker] https://[2606:4700:4700::1111]/dns-query ❌
[Network Checker] https://cloudflare-dns.com/dns-query ✔️
[Login] 请按以下步骤进行操作:
注意: 程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号
1. 访问「https://app-api.pixiv.net/web/v1/login?code_challenge=KvKHredQGWeNG1J1tJ-Hm1Zh4Jei61UZ0dxW2N9Z09k&code_challenge_method=S256&client=pixiv-android」
   (若您别无他法，还是不能访问以上网址，那可参考此方式 https://github.com/mashirozx/Pixiv-Nginx 先进行配置)
2. 打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
3. 开启「Preserve log / 持续记录」
4. 在「Filter / 筛选」文本框中输入「callback?」
5. 登录您的 Pixiv 账号
6. 成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段
7. 将「code」后面的参数输入本程序
Code: kwJtxfyyHac5cib7VIWArDrhOMP4wWT9L560SEWXNug
!Error at 2021-10-31 01:05:04:
Traceback (most recent call last):
  File "C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a/app/lib/core/biu.py", line 154, in __login
    self.__loginAppAPI(**args)
  File "C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a/app/lib/core/biu.py", line 255, in __loginAppAPI
    self.api.login(username, password)
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\pixivpy3\api.py", line 75, in login
    return self.auth(username=username, password=password)
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\pixivpy3\api.py", line 117, in auth
    raise PixivError(
pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1061, in _create
    self._sslobj = self._context._wrap_socket(
ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='public-api.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError(0, 'Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a/app/lib/common/login_helper/main.py", line 77, in login
    return self.tokenG.login(host=self.authTokenURL, newCode=True, kw=kw)
  File "C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a\app\lib\common\login_helper\token.py", line 71, in login
    response = self.requests.post(
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='public-api.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError(0, 'Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)')))

[PixivBiu] 获取 Token 时出错，请重试。
按任意键退出...

**Comment by txperl** [comment]
> 感谢大佬们的回复，后面我再用留空的方法可以下一步了。  推测是网络的问题。
> 
> 
> 
> 但是输入token 后 报错ssl error？
> 
> 试过好几次，应该不是超时。。
> 
> 
> 
> 
> 
> ### C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a>python main.py
> 
> [PixivBiu] 已启用系统代理地址: 127.0.0.1:10809
> 
> [PixivBiu] 检测网络状态...
> 
> [PixivBiu] 无法访问 Pixiv，启用 byPassSni API
> 
> [PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
> 
> 是否开始手动获取 Token 后继续使用? (y / n): y
> 
> [Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
> 
> [Login Helper] 开始进行网络检测...
> 
> 检测到内容为 127.0.0.1:10809 的代理监听地址，是否需要更改? (y / n): y
> 
> 请输入代理监听地址(可留空):
> 
> [Network Checker] https://public-api.secure.pixiv.net ✔️
> 
> [Network Checker] https://1.0.0.1/dns-query ✔️
> 
> [Network Checker] https://1.1.1.1/dns-query ✔️
> 
> [Network Checker] https://[2606:4700:4700::1001]/dns-query ❌
> 
> [Network Checker] https://[2606:4700:4700::1111]/dns-query ❌
> 
> [Network Checker] https://cloudflare-dns.com/dns-query ✔️
> 
> [Login] 请按以下步骤进行操作:
> 
> 注意: 程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的，且 Code 不带有引号
> 
> 1. 访问「https://app-api.pixiv.net/web/v1/login?code_challenge=KvKHredQGWeNG1J1tJ-Hm1Zh4Jei61UZ0dxW2N9Z09k&code_challenge_method=S256&client=pixiv-android」
> 
>    (若您别无他法，还是不能访问以上网址，那可参考此方式 https://github.com/mashirozx/Pixiv-Nginx 先进行配置)
> 
> 2. 打开浏览器的「Dev Console / 开发者工具 / F12」，切换至「Network / 网络」标签
> 
> 3. 开启「Preserve log / 持续记录」
> 
> 4. 在「Filter / 筛选」文本框中输入「callback?」
> 
> 5. 登录您的 Pixiv 账号
> 
> 6. 成功登录后，会出现一个类似「https://app-api.pixiv.net/.../callback?state=...&code=...」的字段
> 
> 7. 将「code」后面的参数输入本程序
> 
> Code: kwJtxfyyHac5cib7VIWArDrhOMP4wWT9L560SEWXNug
> 
> !Error at 2021-10-31 01:05:04:
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a/app/lib/core/biu.py", line 154, in __login
> 
>     self.__loginAppAPI(**args)
> 
>   File "C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a/app/lib/core/biu.py", line 255, in __loginAppAPI
> 
>     self.api.login(username, password)
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\pixivpy3\api.py", line 75, in login
> 
>     return self.auth(username=username, password=password)
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\pixivpy3\api.py", line 117, in auth
> 
>     raise PixivError(
> 
> pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
> 
> HTTP 400: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
> 
>     httplib_response = self._make_request(
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
> 
>     self._validate_conn(conn)
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
> 
>     conn.connect()
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 416, in connect
> 
>     self.sock = ssl_wrap_socket(
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
> 
>     ssl_sock = _ssl_wrap_socket_impl(
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
> 
>     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
> 
>     return self.sslsocket_class._create(
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1061, in _create
> 
>     self._sslobj = self._context._wrap_socket(
> 
> ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
> 
>     resp = conn.urlopen(
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
> 
>     retries = retries.increment(
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 574, in increment
> 
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> 
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='public-api.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError(0, 'Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)')))
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a/app/lib/common/login_helper/main.py", line 77, in login
> 
>     return self.tokenG.login(host=self.authTokenURL, newCode=True, kw=kw)
> 
>   File "C:\Users\wyzhw\Downloads\PixivBiu-2.1.2a\app\lib\common\login_helper\token.py", line 71, in login
> 
>     response = self.requests.post(
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 590, in post
> 
>     return self.request('POST', url, data=data, json=json, **kwargs)
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
> 
>     resp = self.send(prep, **send_kwargs)
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
> 
>     r = adapter.send(request, **kwargs)
> 
>   File "C:\Users\wyzhw\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 514, in send
> 
>     raise SSLError(e, request=request)
> 
> requests.exceptions.SSLError: HTTPSConnectionPool(host='public-api.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLError(0, 'Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)')))
> 
> 
> 
> [PixivBiu] 获取 Token 时出错，请重试。
> 
> 按任意键退出...

本地的 `./usr/` 文件夹下有 `.token.json` 文件吗？

**Comment by aaaihw** [comment]
嗯，我有创建json 里面放code。 
运行main.py 还会输入一遍 code。
然后报错还是这个，，，，
欸 可能是我不这里不行吧 。 
搞不定！！！！

**Comment by txperl** [comment]
> 嗯，我有创建json 里面放code。 
> 
> 运行main.py 还会输入一遍 code。
> 
> 然后报错还是这个，，，，
> 
> 欸 可能是我不这里不行吧 。 
> 
> 搞不定！！！！ 

不用手动创建 `.token.json` 文件，手动创建也是无用的。

如果可以的话，你可以先删除，然后再次尝试登录，检查一下程序有没有正常生成 `.token.json` 文件。这样我好做一个判断。

**Comment by aaaihw** [comment]
> > 嗯，我有创建json 里面放code。
> > 运行main.py 还会输入一遍 code。
> > 然后报错还是这个，，，，
> > 欸 可能是我不这里不行吧 。
> > 搞不定！！！！
> 
> 不用手动创建 `.token.json` 文件，手动创建也是无用的。
> 
> 如果可以的话，你可以先删除，然后再次尝试登录，检查一下程序有没有正常生成 `.token.json` 文件。这样我好做一个判断。

我 把他删了，然后又重新运行了一边。usr里只有static 和 templates 没有生产.token.json

**Comment by txperl** [comment]
> > > 嗯，我有创建json 里面放code。
> > > 运行main.py 还会输入一遍 code。
> > > 然后报错还是这个，，，，
> > > 欸 可能是我不这里不行吧 。
> > > 搞不定！！！！
> > 
> > 
> > 不用手动创建 `.token.json` 文件，手动创建也是无用的。
> > 如果可以的话，你可以先删除，然后再次尝试登录，检查一下程序有没有正常生成 `.token.json` 文件。这样我好做一个判断。
> 
> 我 把他删了，然后又重新运行了一边。usr里只有static 和 templates 没有生产.token.json

登陆成功了吗？

**Comment by aaaihw** [comment]
没有。。

**Comment by aaaihw** [comment]
> > > > 嗯，我有创建json 里面放code。
> > > > 运行main.py 还会输入一遍 code。
> > > > 然后报错还是这个，，，，
> > > > 欸 可能是我不这里不行吧 。
> > > > 搞不定！！！！
> > > 
> > > 
> > > 不用手动创建 `.token.json` 文件，手动创建也是无用的。
> > > 如果可以的话，你可以先删除，然后再次尝试登录，检查一下程序有没有正常生成 `.token.json` 文件。这样我好做一个判断。
> > 
> > 
> > 我 把他删了，然后又重新运行了一边。usr里只有static 和 templates 没有生产.token.json
> 
> 登陆成功了吗？

没有，，

**Comment by txperl** [comment]
网络问题，你可以检查一下你的代理设置，或者试一下用手机的移动网络。

**Comment by txperl** [comment]
新版本增加了更多的 DoH 服务器，可以直接用打包好的程序试一下。
