### ISSUE TITLE
在登录后再次打开命令行会闪退，浏览器显示无法访问127.0.0.1

### ISSUE THREAD

**Issue by Waximell** [txperl/PixivBiu#23]
我在退出的一瞬间截取到了这个：
![屏幕截图 2021-11-15 034711](https://user-images.githubusercontent.com/59529964/141696868-7d119e87-2211-485c-bb70-e6539db2555f.png)

**Comment by txperl** [comment]
这个错误应该是 `4001` 端口被占用引起的。

「在登录后再次打开命令行」，指的是有重复打开 PixivBiu 吗？

**Comment by Waximell** [comment]
登录应当是正常登录了，我印象里显示成功了，“登录后再次打开命令行”指的是直接点pixivbiu.exe。我不是开发人员，所以选择了打包好的releases。

我尝试过更换至4002端口，但是获得的结果是一样的。

另外，我查看了端口的占用情况，4001与4002端口并未被占用。

关于可能的原因，似乎与WSA（安卓子系统）有关，开机先打开pixivbiu则有时可以打开，开启WSA后再开启pixivbiu则打不开，而且我还发现我的WSA现在已经无法正常打开子系统的应用窗口了。但以上问题并不100%复现。我猜测WSA可能是把4001、4002等端口作为了显示输出端口，望调查。

PS.我不清楚如何在GitHub上回复您，便回复了邮件，希望没有打扰到你。

发自我的iPhone

**Comment by txperl** [comment]
我觉得多半是系统虚拟机占用了几个端口段，之前我也遇到过类似情况。

可以尝试把 PixivBiu 的端口改得大一些，比如 40010 这种。

不打扰不打扰。在 GitHub 回复的话，可以在你提的这个 Issue 页面直接回复。或者在 GitHub 个人主页右上角有消息图标，可以看到别人是否回复了您。不过，直接回复邮件的话，GitHub 会自动把你的邮件答复提交到相应的 Issue 中。

**Comment by Waximell** [comment]
我将端口改到了40010，两边都可以正常使用了，非常感谢！

**Comment by txperl** [comment]
不客气。
