### ISSUE TITLE
请教，没有找到callback

### ISSUE THREAD

**Issue by diklios5768** [txperl/PixivBiu#24]
进行到查找code那一步的时候，筛选没有找到callback(我确认是打开了网络之后再请求的，没过滤之前有很多的返回)

![image](https://user-images.githubusercontent.com/47837462/142227735-313a537b-0c79-4357-99b6-5edf3704ae23.png)

![image](https://user-images.githubusercontent.com/47837462/142228142-1ebf7093-5990-432a-a47f-046eca21c388.png)

**Comment by txperl** [comment]
请问你登录后页面跳转了吗？如果有的话，可以检查一下自己是否开启了持续记录选项。

**Comment by diklios5768** [comment]
> 请问登录后页面跳转了吗？如果有的话，可以检查一下自己是否开启了持续记录选项。

跳转了，页面是这样的
![image](https://user-images.githubusercontent.com/47837462/142357222-6719faaa-5b9e-4431-9d6d-a64a9c4e0cd6.png)

请问一下持续记录选项是在哪里，不了解
![image](https://user-images.githubusercontent.com/47837462/142357279-25d93e8c-91d4-4219-a1ef-26a68e63bc2e.png)

**Comment by txperl** [comment]
把那个「保留日志」打开应该就可以了。

**Comment by diklios5768** [comment]
> 把那个「保留日志」打开应该就可以了。

我试了，强制刷新了一遍还是没有
![image](https://user-images.githubusercontent.com/47837462/142358929-d467168b-9486-4c46-b02c-6596beb39aca.png)

**Comment by txperl** [comment]
页面上点了「继续使用此账号」了吗？

**Comment by diklios5768** [comment]
> 页面上点了「继续使用此账号」了吗？

没点(⊙﹏⊙)，感谢提醒

**Comment by txperl** [comment]
解决了吗？

**Comment by diklios5768** [comment]
> 解决了吗？
解决了，感谢

**Comment by txperl** [comment]
ok
