### ISSUE TITLE
获取 Token 时出错，请重试。

### ISSUE THREAD

**Issue by xinxinyihao** [txperl/PixivBiu#26]
![7582cf5232eac0d7ce60c2dc8ecb2ec](https://user-images.githubusercontent.com/41506567/147205287-c120b3c3-1530-4afd-b670-982c230d22ae.png)
老师，我获取了token后一直提示这个错误，我已经重新获取很多个了，token也没有输入错误，还是一直这样，肿么了嘛

**Comment by txperl** [comment]
可以告知一下您的 Code 是在哪里复制的嘛？可以截个图然后将 Code 打个码就好。

**Comment by xinxinyihao** [comment]
> 可以告知一下您的 Code 是在哪里复制的嘛？可以截个图然后将 Code 打个码就好。

![image](https://user-images.githubusercontent.com/41506567/147209418-1ac62fe1-42f1-4a4c-b7c1-3567a2e33481.png)
老师你回答的也太快了吧，辛苦了，在这个地方获得的。

**Comment by txperl** [comment]
hhh 正好那时候看到了，老师这称呼让我有些受宠若惊...

操作确实没有错误，请问你的 Code 开头有没有包含「=」符号？这是不需要的。

**Comment by xinxinyihao** [comment]
> hhh 正好那时候看到了，老师这称呼让我有些受宠若惊...
> 
> 操作确实没有错误，请问你的 Code 开头有没有包含「=」符号？这是不需要的。

没有，我就是复制了，然后粘贴上去，就是不行，俺也不懂。

**Comment by txperl** [comment]
震惊... 我本地没有问题。（（

程序没有报错而是显示原因，说明请求成功但服务器返回了 Code 错误代码。

再... 试一次看看？或者可以通过邮箱私信我一下，我发给你一个可以 debug 的版本试一下。之后会在日志方面多优化的，反馈的时候就不会很麻烦了，抱歉。

**Comment by xinxinyihao** [comment]
> 震惊... 我本地没有问题。（（
> 
> 程序没有报错而是显示原因，说明请求成功但服务器返回了 Code 错误代码。
> 
> 再... 试一次看看？或者可以通过邮箱私信我一下，我发给你一个可以 debug 的版本试一下。之后会在日志方面多优化的，反馈的时候就不会很麻烦了，抱歉。

啊拉拉，老师你也太客气了，用你的东西，你还和我说抱歉，让我情何以堪，哈哈哈。没有在纠结这个问题了。我在国外的服务器上搞了一把，成功了。老师你啥时候更新一下文档呀，感觉好多地方不太一样，我又是半桶水，自己也看不太懂。
我现在可以正常打开web页面了，我想知道那个api是怎么使用的。我用  http://ip+端口+api，啥都得不到。
如：http://ip:端口/api/biu/get/status，得到这个结果：
![image](https://user-images.githubusercontent.com/41506567/147307209-6d399753-9186-45d2-8e1f-b7647b46b004.png)
如何正确访问api，还请老师指条明路。非常感谢。

**Comment by xinxinyihao** [comment]
> 震惊... 我本地没有问题。（（
> 
> 程序没有报错而是显示原因，说明请求成功但服务器返回了 Code 错误代码。
> 
> 再... 试一次看看？或者可以通过邮箱私信我一下，我发给你一个可以 debug 的版本试一下。之后会在日志方面多优化的，反馈的时候就不会很麻烦了，抱歉。

老师能否更新一下api的文档，请求参数部分，有些能看懂啥意思，有些就看不懂了，非常感谢

**Comment by txperl** [comment]
好的，近期会完善部分文档的。不过当时写的时候 API 并没有什么设计，导致比较杂乱... 文档到时候可能也是乱乱的。

如果比较着急的话，可以去 `./app/plugin` 那个文件中查看，或者直接通过前端请求来猜猜。（（

总之最近会有的！hhh
