### ISSUE TITLE
关于如何访问web端的问题

### ISSUE THREAD

**Issue by AndoKaguya** [txperl/PixivBiu#27]
作者，你好，通过指引，已成功搭建并运行，但是我是建在了境外服务器上，并且防火墙均已开通4001端口，访问境外服务器ip:4001显示ERROR 503，无法访问，请问我还需要做哪些操作处理？

**Comment by txperl** [comment]
如果只是自用的话，可以简单将 `sys.host` 配置项修改成 `0.0.0.0:4001`，这样你就可以直接通过 `ip:4001` 访问了。

https://github.com/txperl/PixivBiu/blob/fae393b8ae446530775674278c77178a87bcd213/config.yml#L9

如果有其他需求，可以用 NGINX 等做个中间层，具体可以搜索关键词「nginx flask」。

**Comment by AndoKaguya** [comment]
谢谢！改成 `0.0.0.0` 之后成功访问了~

**Comment by AndoKaguya** [comment]
作者，我还想请教一个问题，如何在nginx配置域名反代pixivbiu呢？
我做了一个基本的配置，但是访问后页面失去了布局和功能
```
#PROXY-START/
location  ~* \.(gif|png|jpg|css|js|woff|woff2)$
{
    proxy_pass http://0.0.0.0:40011;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    expires 12h;
}
location /
{
    proxy_pass http://0.0.0.0:40011;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    
    add_header X-Cache $upstream_cache_status;
    
    #Set Nginx Cache
    
    	add_header Cache-Control no-cache;
}

#PROXY-END/
```
![image](https://user-images.githubusercontent.com/53990829/147213246-cc7d7fd8-33ae-4321-8794-0f5d2f729806.png)

**Comment by txperl** [comment]
你的配置应该是对于资源访问控制（`location  ~* \.(gif|png|jpg|css|js|woff|woff2)`）错了，可以再看看网上是怎么配置的。

如果只是想可以访问，不需要设置资源缓存或访问控制的话，我就贴个最基础的。我对于它也不是很熟悉...

```nginx
server
{
    listen 80;
    server_name {your_domain_name};
    
    location / {
        proxy_pass {your_program_address};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

- `{your_domain_name}` 替换成你的域名
- `{your_program_address}` 替换成程序的运行地址（如 `http://127.0.0.1:4001`）

顺便一提，如果用了 NGINX 做转发，程序运行地址（`sys.host`）不建议使用 `0.0.0.0`，可以改为 `127.0.0.1`。

**Comment by AndoKaguya** [comment]
感谢作者，经过一顿排查之后，是其他细节设置出问题了，反代上是没有问题的~

**Comment by txperl** [comment]
解决了就好。
