### ISSUE TITLE
始终出错，确定code无误

### ISSUE THREAD

**Issue by z0z0r4** [txperl/PixivBiu#28]
![image](https://user-images.githubusercontent.com/78744121/147724491-8e036985-104f-4623-8766-9b9ffd45f5b4.png)
代理无误，正常访问Google
![image](https://user-images.githubusercontent.com/78744121/147724515-cc23ab35-0462-45c1-930e-1e9911bdbf16.png)
不明白为什么，code是copy value的，也没问题

**Comment by z0z0r4** [comment]
另外这是什么意思？似乎无法访问
`访问运行地址，默认为 http://127.0.0.1:4001/`
![image](https://user-images.githubusercontent.com/78744121/147724726-4cd518f9-ada8-448f-bfdf-7699b542f379.png)

**Comment by z0z0r4** [comment]
其次pip install -r requirements.txt 似乎无法安装好这些库？centos 8系统，pip3
![image](https://user-images.githubusercontent.com/78744121/147724952-6cec9a00-0fcf-41df-af17-6a1c69171be7.png)

**Comment by z0z0r4** [comment]
排除网络问题，坐标洛杉矶
![image](https://user-images.githubusercontent.com/78744121/147725297-4ac65f0a-ad7c-4527-8afe-f2e880b3629a.png)

**Comment by txperl** [comment]
请问显示登录失败后的 `./usr` 目录下包含 `.token.json` 文件吗？

**Comment by z0z0r4** [comment]
[root@box9618 PixivBiu]# cat .token.json
cat: .token.json: No such file or directory
无

**Comment by z0z0r4** [comment]
需要如何解决？

**Comment by txperl** [comment]
不要意思最近没有查看消息。

我暂时也不是很清楚为何会这样... 程序没有直接报错说明 Pixiv 服务器返回了登录失败代码，是服务器程序拒绝导致的登录失败。

大部分人都可以正常登录的，但确实有个例遇到和你相同的问题。解决方法也很迷，如切换网络、切换运行设备、切换账号等。如果可以的话，我建议可以尝试一下换个账号登录。

抱歉。

**Comment by z0z0r4** [comment]
好吧...
