### ISSUE TITLE
鸡肋，以及改进建议

### ISSUE THREAD

**Issue by Macaron-Lawrence** [txperl/PixivBiu#31]
不太行，所谓的收藏数搜索只是搜索类似”オリジナル500users入り“这样的标签，不包含类似标签的作品无法被搜索到
建议参考https://github.com/upbit/pixivpy，通过api真正意义上获取作品的收藏数，然后进行筛选展示
而排序也只是单页面排序

**Comment by txperl** [comment]
你提到的收藏数搜索、排序这些功能，只有在开通了 Pixiv 会员才能实现，即便使用了 API 也是无法绕过的。

收藏数搜索在好几年前是全部用户都可以使用的，近几年才改成了会员专属功能。不过有好心的用户会把特定收藏数区间的作品贴上指定 tag 以让非会员用户筛选，我觉得这已经无可厚非了。

对于排序，程序只是一下子搜索多页，然后在这几页的结果中进行排序。如果你觉得结果不全，那可以把「每组页数」数值调大。如果接近总页数，大概率也能达到会员的效果，但这样一次搜索会很慢。

我目前只知道唯有开通 Pixiv 会员才能实现上述功能，如果有绕开的方法请告知，程序会改进的。
