### ISSUE TITLE
clash系统代理下无法使用，v2ray可以

### ISSUE THREAD

**Issue by z0z0r4** [txperl/PixivBiu#32]
![image](https://user-images.githubusercontent.com/78744121/168419665-ca0f4904-dc7b-491d-976a-f19ef82fe0b4.png)
![image](https://user-images.githubusercontent.com/78744121/168419685-a4b90c86-35d7-46cb-9b40-edc4aa6802ad.png)
![ULFU1WKQ`9_)CQFE7HQX{~N](https://user-images.githubusercontent.com/78744121/168419727-1602b355-6590-4043-90a4-e8e918cc38d5.png)

访问外网正常
![image](https://user-images.githubusercontent.com/78744121/168419698-f2d180f6-2daa-4030-a2a1-9499ec2ebae6.png)

然而V2ray良好，这离谱

部分报错
![image](https://user-images.githubusercontent.com/78744121/168419721-d0ccf93e-60b6-40fd-a82d-86c4c1c3bd76.png)

**Comment by txperl** [comment]
自动检测到的代理地址出错了，手动设置一下就能正常使用了。

之后会修复的，感谢反馈。

**Comment by z0z0r4** [comment]
Thanks
（需要怎么手动设置...？我觉得不应该就是这样的？
![image](https://user-images.githubusercontent.com/78744121/168463543-c68951bf-cf7c-4594-86e5-d98f184aa6fe.png)
麻了

**Comment by txperl** [comment]
> Thanks （需要怎么手动设置...？我觉得不应该就是这样的？ ![image](https://user-images.githubusercontent.com/78744121/168463543-c68951bf-cf7c-4594-86e5-d98f184aa6fe.png) 麻了

程序不支持这种格式的代理配置。如果需要手动设置的话，在程序提示更改时输入 `y` 即可。
