### ISSUE TITLE
(Feature Request) An online version of PixivBiu

### ISSUE THREAD

**Issue by pyramidjack** [txperl/PixivBiu#34]
Hey. Ya think you can make an online version of PixivBiu similar to Furarchiver?: https://furarchiver.net/

The main reason why I'm asking this is because there's literally no Archiver Site that downloads entire galleries from Pixiv. Perhaps you could do some actual justice by creating an online version of PixivBiu similar to Furarchiver?

**Comment by txperl** [comment]
It's a good idea and I think it can be achieved not so difficult.

However, the server which should operate it might be a matter. Just like Furarchiver, it needs large storage, enough network IO and so more. It will cost a lot...
