### ISSUE TITLE
到底要怎么调整网络啊？

### ISSUE THREAD

**Issue by zoukai333** [txperl/PixivBiu#35]
[Altfe] ;)
[PixivBiu] 由于 Pixiv 禁止了账号密码登陆方式，暂时只能使用 Token 进行登录
是否继续? (y / n): y
[Login Helper] 即将开始进行网络检测，此过程可以减少因网络问题导致的无法正常使用 PixivBiu 的概率
[Login Helper] 开始进行网络检测...
未能检测到代理地址，是否需要手动设置? (y / n): y
请输入代理监听地址(可留空):
[Network Checker] https://public-api.secure.pixiv.net [failed]
[Network Checker] https://1.0.0.1/dns-query [failed]   （这行偶尔是绿的，但是单单这行绿有时能用有时不能用）
[Network Checker] https://1.1.1.1/dns-query [failed]
[Network Checker] https://doh.dns.sb/dns-query [failed]
[Network Checker] https://cloudflare-dns.com/dns-query [failed]
[PixivBiu] 您的网络无法正常进行 Pixiv Token 登陆，请调整后重试。
按任意键退出...

**Comment by zoukai333** [comment]
![}PZX1GXT@20MAL`O~P81%%7](https://user-images.githubusercontent.com/112177732/186905124-ec70fa31-d059-4793-9313-aa55557f8d94.png)
彻底弄不明白了，这俩同时开的

**Comment by txperl** [comment]
如果不清楚相关代理工具的话，询问 `未能检测到代理地址，是否需要手动设置?` 这个选项时选择 `n` 就好了。

不使用代理的话，如果出现如图二的情况，那本地网络可能有些问题，无法连接到指定服务器。有时候可能会出现图一的情况，那说明网络这时候又能正常连接服务器了，但不是太稳定。

要稳定使用的话还是需要代理工具，但这就不属于本程序的范畴了。

**Comment by zoukai333** [comment]
谢谢
