### ISSUE TITLE
希望可以添加两个筛选功能qwq

### ISSUE THREAD

**Issue by FuYang001** [txperl/PixivBiu#37]
你好作者大大，请问可以添加两个筛选功能吗？例如剔除r18内容，以及只保留固定浏览数或收藏数以上的插画qwq

**Comment by txperl** [comment]
可以的，会在近期更新中加入的。

🎑 中秋快乐，哈哈哈 qwq。

**Comment by FuYang001** [comment]
> 可以的，会在近期更新中加入的。
> 
> 🎑 中秋快乐，哈哈哈 qwq。

感谢作者大大，中秋快乐！🎑

**Comment by txperl** [comment]
已经在 2.5.3 版本中加入了这两项功能，可以在 [GitHub Releases](https://github.com/txperl/PixivBiu/releases) 里下载。

qwq
