### ISSUE TITLE
奇怪的更新提示

### ISSUE THREAD

**Issue by z0z0r4** [txperl/PixivBiu#38]
![%BI7 `CKGBF{7 PT%OH6YP6](https://user-images.githubusercontent.com/78744121/192078896-aa72c596-7933-4d99-bc8c-6ea3e5089140.png)
2.53a已经是最新版了吧？
![$Y8}Q9MJS$@`0S8%QFR~_SX](https://user-images.githubusercontent.com/78744121/192078904-1764b2c1-a89e-4a2a-9932-5ffed2bfe21f.png)
呆滞.jpg
![KZ@UF$ CP9Q8Q2CJDI V~UA](https://user-images.githubusercontent.com/78744121/192078907-c1a86a7c-a15e-4ac9-a078-a5c9a2c8080f.png)

**Comment by z0z0r4** [comment]
![%BI7 `CKGBF{7 PT%OH6YP6](https://user-images.githubusercontent.com/78744121/192078916-b8c549a2-3fd9-4e6c-8308-0a102415b801.png)

**Comment by txperl** [comment]
应该是检测更新时因为网络问题失败了，然后就默认显示有更新了…
