### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by Chen-da-x** [txperl/PixivBiu#39]
老师，能否帮我看下：
输入正确token后任然无法访问，提示Error: 'bool' object is not subscriptable.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/84442753/192154980-6433aaac-31ef-491e-a809-e7d68e4fd4e1.png">

**Comment by txperl** [comment]
看起来 Token 获取是成功了，但主要的问题出在 `.token.json` 文件保存失败了...

我暂时还未遇到过这种情况，可以试试打包好的程序或者换个 Python 环境？

**Comment by txperl** [comment]
最新版本中改善了部分可能的登录问题，可以试试看。
