### ISSUE TITLE
前几天开始显示帐密错误

### ISSUE THREAD

**Issue by FungJiHsu** [txperl/PixivBiu#4]
https://img.nga.178.com/attachments/mon_202010/08/-9lddQ5-24gyKoT3cSrl-ef.jpg

**Comment by txperl** [comment]
很多人向我反馈了同样的问题。

我测试了一下，发现用 byPassSni API 确实登录不了。应该是这方法失效了，但这个问题我需要再看看，之后会尝试解决的。

现在暂时的解决方法是：如果有代理的话，在配置文件中设置一下代理地址，之后就可以正常使用了。

感谢！

**Comment by FungJiHsu** [comment]
> 很多人向我反馈了同样的问题。
> 
> 我测试了一下，发现用 byPassSni API 确实登录不了。应该是这方法失效了，但这个问题我需要再看看，之后会尝试解决的。
> 
> 现在暂时的解决方法是：如果有代理的话，在配置文件中设置一下代理地址，之后就可以正常使用了。
> 
> 感谢！

设置代理以后可行
