### ISSUE TITLE
[BUG] 自定义图片反代地址出错 [Feature] config.yml 中提供单独默认反代地址设置

### ISSUE THREAD

**Issue by z0z0r4** [txperl/PixivBiu#40]
主页设置反代地址后就报错
![image](https://user-images.githubusercontent.com/78744121/193300713-28d407a6-553f-4a8b-a42d-74e18fe9c917.png)

疑似某处的 replace 使用了`PixivBiu 网址+反代地址+图片路径`，但看不懂 Web :(
![image](https://user-images.githubusercontent.com/78744121/193300589-1eaec55c-b93c-476e-ae0b-6d2828908e24.png)

设置反代地址为 `i.pixiv.example.com`
PixivBiu 网址为 `127.0.0.1:4001`
则图片最终为 `http://127.0.0.1:4001/i.pixiv.example.com/c/~~~`

莫名其妙多出的 PixivBiu 网址...急需修复？

[Feature] config.yml 中提供单独默认反代地址设置，而非只有下载使用的服务器...

**Comment by txperl** [comment]
已在最新版本中完善了这个问题，感谢反馈。
