### ISSUE TITLE
token error

### ISSUE THREAD

**Issue by little-liquid-nougat** [txperl/PixivBiu#43]
hello, 
When I start the program for the first time and it asks me for the Pixiv token and I do all the steps to get it and copy it, it shows me this every time.

" [PixivBiu] Code error. Please note that the program requires a different code each time it starts, and cannot reuse the previous one, and the Code doesn't contain quotation marks.
[PixivBiu] There was an error getting the Token, please try again. "

but I never used the token before

Is there anyone who can help me ?
![Image 11-01-23 à 07 04](https://user-images.githubusercontent.com/122428083/211730260-2ecb5df5-526e-40d1-a9b9-a977450fc417.jpg)

**Comment by little-liquid-nougat** [comment]
I tried several times to redo the operation from the beginning, trying to add "code =", "=" or the token alone, but I always get the same result

**Comment by txperl** [comment]
Suppose now there is a URL that `https://pixiv/.../?code=xyz`.

Dose the "token alone" means `xyz`?

**Comment by little-liquid-nougat** [comment]
<img width="1082" alt="Capture d’écran 2023-01-11 à 16 38 23" src="https://user-images.githubusercontent.com/122428083/211849535-81aa9ff5-76f6-4823-8572-e59cdaa66618.png">

**Comment by little-liquid-nougat** [comment]
There is an exemple of "token alone", but nothing change

**Comment by little-liquid-nougat** [comment]
my version is the "PixivBiu_v2.6.1a_mac_intel"

**Comment by txperl** [comment]
The format of code you inputted is right.

Actually, I don't know how to resolve this issue either... This error is due to the response of Pixiv which says the code sent is wrong. But in your case, the code should be right.

You could register another Pixiv account and try to login.

Or, if you have time, I could send you a test program that could catch more details of the error.

**Comment by little-liquid-nougat** [comment]
I tried with another pixiv account, but nothing changes

**Comment by little-liquid-nougat** [comment]
I am free at the moment, because I was in class

**Comment by little-liquid-nougat** [comment]
I am still available for 8 hours

**Comment by little-liquid-nougat** [comment]
So, it's whenever you want it

**Comment by little-liquid-nougat** [comment]
I managed to make it work
I just changed the language of the login page from English to Chinese.

**Comment by little-liquid-nougat** [comment]
and it works now

**Comment by txperl** [comment]
Sorry... I'm in China (UTC+8), so the free time of ours may be not overlapped too much.

Wow, that's great. But I tried get the code in the English page, and it worked too. I guess the main reason is something wrong about the network component used by the program. I will keep digging and try to fix it.

Thanks for your feedback and trying.

**Comment by txperl** [comment]
Set `sys.host` to `0.0.0.0:4001` in the `config.yml` file, and you could visit `http://your_public_ip:4001` to use the program.

The `4001` above is the port you want.

Or, if you have a web server (e.g. Apache, NGINX), you could forward a local address to the public via reverse proxy.

**Comment by little-liquid-nougat** [comment]
Ok,thanks.
I will try later
