### ISSUE TITLE
我想请问一下关于token获取的问题

### ISSUE THREAD

**Issue by hhhuskytc** [txperl/PixivBiu#47]
我仅使用了源代码中的login()函数，想通过源代码搞懂P站的登陆规则，但是仅使用login()函数一直返回错误信息，如下：

Response: {'has_error': True, 'errors': {'system': {'message': '不正なリクエストです。', 'code': 918}}, 'error': 'invalid_request'}

每次产生的token都是我通过重新登陆进行复制的，电脑后台开了代理，但是没有一次成功的登陆。
我想请问一下在登陆之前还需要运行其他的函数获取什么信息吗？单独运行login函数可以实现登陆的操作吗？还是我的token获取方法有什么错误

**Comment by txperl** [comment]
大部分登录步骤都封装在 `login_helper` 那里。

如果你指的 `login` 就是它其中的函数，那应该没其他什么需要的了，单独运行是可以正常获取 token 的。

从你贴出的这段返回内容来看，发送的请求参数和步骤应该没啥问题，再检查一下 code 有没有弄错？或者换个账号试试。
