### ISSUE TITLE
对于下载功能的一点建议

### ISSUE THREAD

**Issue by silist** [txperl/PixivBiu#5]
感谢作者开发出这样好用的工具，最近一直在用它下图。不过在我的网络环境下（国内走反代、不使用代理、小水管），一次下载大量图片时有时会出现一些问题：
1. 下载速度波动较大，有时只有几十KBps；
2. 一些大图片可能只能成功下载一部分； 
3. 部分图片始终无法下载完成，导致程序阻塞，无法正常退出。

为了获得更好的下载体验，我这边尝试使用 [aria2](https://github.com/aria2/aria2) 作为下载中间件，aria2开启rpc模式启动；Python部分修改了`app\plugin\biu\do\dl.py`部分的代码，下载时不直接用requests get，而是通过jsonrpc将需要下载的URL、目标文件夹、文件名POST给aria2处理。
这样做的优点和缺点也比较明显：
+ 优点：
1. 可以享受到aria2的优秀下载性能，速度更稳定，并支持断点续传等特性；
2. 可以配合AriaNG等web UI实现对于下载任务的监控和管理；
3. 由于下载交给了aria2，Python程序这边的压力较小，运行更流畅。
+ 缺点：
1. 由于下载请求直接POST给了aria2，因此需要获得下载状态的功能难以直接实现，主要在于更新前端的status和下载动图后的解压合并。
对于以上缺点，好像也可以使用aria2的hook event处理，不过我这边偷懒没有深究...

总之，如果有和我一样遇到下载问题的朋友，可以考虑上面这种使用aria2的方案，目前我个人的体验还是不错的。

**Comment by txperl** [comment]
确实，将下载任务交给 aira2 可以大幅提高下载体验，会在之后的版本中加入的。

感谢反馈以及提供的方案思路！

**Comment by txperl** [comment]
已在新版本中支持 aria2 下载，抱歉拖了很久。（（
