### ISSUE TITLE
说明页面寄了，外加疑惑

### ISSUE THREAD

**Issue by r78ik7** [txperl/PixivBiu#55]
https://biu.tls.moe/#/usage/basic404了
另外，希望能搞一些指南类似的东西（就比如我这种蠢b还没研究明白如何在tag里按收藏排序
另另外，图片数量貌似是不够的，搜了一下舰b的tag，10万以上收藏的啥也没显示
但是不得不说，这是我见过的独立小项目里面ui最舒服的，加油

**Comment by txperl** [comment]
那个页面是我去掉了，因为内容比较老了，也不太想写使用相关的文档了...

要在所有类目里按照收藏数排序的话，可以把 `筛选-排序模式` 改成 `0s` 就好了。

图片数量的问题，我也不知道是 API 不同还是什么导致的。但你说的 “10 万以上” 这个是怎么搜索的呢？

谢谢啦。

**Comment by IMBAepsilon** [comment]
> 那个页面是我去掉了，因为内容比较老了，也不太想写使用相关的文档了...
> 
> 要在所有类目里按照收藏数排序的话，可以把 `筛选-排序模式` 改成 `0s` 就好了。
> 
> 图片数量的问题，我也不知道是 API 不同还是什么导致的。但你说的 “10 万以上” 这个是怎么搜索的呢？
> 
> 谢谢啦。

印象中一个基础的搜索收藏量的手段是通过 `XXXusers入り`  例如 `100000users入り` 
似乎是通过添加tag实现的（？）

**Comment by txperl** [comment]
> > 那个页面是我去掉了，因为内容比较老了，也不太想写使用相关的文档了...
> > 要在所有类目里按照收藏数排序的话，可以把 `筛选-排序模式` 改成 `0s` 就好了。
> > 图片数量的问题，我也不知道是 API 不同还是什么导致的。但你说的 “10 万以上” 这个是怎么搜索的呢？
> > 谢谢啦。
> 
> 印象中一个基础的搜索收藏量的手段是通过 `XXXusers入り` 例如 `100000users入り` 似乎是通过添加tag实现的（？）

是的。

最开始 Pixiv 是官方支持这种搜索组合的，可以直接筛选作品的收藏数，但后来这个功能被去掉了。

之后取而代之的，用户会在作品上打上对应收藏数的 tag，然后通过 tag 模式搜索来变相实现。
