### ISSUE TITLE
嘗試在Unraid docker 上安裝失敗

### ISSUE THREAD

**Issue by SA8620** [txperl/PixivBiu#58]
按照官方指示逐步輸入變量
無法啟動docker，已為其提供token 無效
想使用控制台進行輸入也不行
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/cf66fa63-cb99-47aa-97e5-b4f271973921)
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/3f9913e5-2d11-4304-9f6a-0ddd3a7e7951)
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/abb05cd3-19c1-4b8b-87ff-d1764ca20649)
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/5ae924f8-22fc-4ccc-a6fd-2dd6dcbab13e)
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/77d00c86-b0b2-42b3-8342-46e9c7b36338)

**Comment by txperl** [comment]
程序在没有检测到有效的 Token 时，就会开始登录引导步骤，而这些步骤在自启的 Docker 容器里是无法进行的。

看了一下，这个问题出在你提供的 Token 文件内容不对。

要将获取到的 Token 直接放入对应的文件中（并非 JSON 格式），比如下面这样。

```
kw-Tdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

最好也把文件名 `.token.json` 中的 `.json` 去掉，以免以后误解了。

最后别忘了在创建容器时加上映射参数 `-v 本机路径:/Pixiv/usr/.token`。

**Comment by SA8620** [comment]
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/35449097-de8d-4ec0-b897-cf090c9033e5)
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/e6aba8d3-4785-4ba3-8b1d-73ba6daf1187)
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/5ae01041-4b1f-42df-aa37-5b2b74e5cf5a)
容器路徑應該填寫什麼？
我的步驟不知道有沒有做錯，跟你這樣做還是不無法啟動

**Comment by txperl** [comment]
请问你的 `.token` 里的内容是哪里来的？是图中的 Code 还是...

**Comment by SA8620** [comment]
图中的 Code

**Comment by SA8620** [comment]
.token是自己建立的檔案，還是是在哪裡獲取的

**Comment by SA8620** [comment]
這次我嘗試了以這種方式安裝：
docker run -d \
    --name pixivbiu \
    --user $(id -u):$(id -g) \
    -p 4001:80 \
    -e sys.debug=false \
    -e sys.apiRoute="direct" \
    -e sys.proxy="" \
    -e sys.language="" \
    -e sys.theme="multiverse" \
    -e biu.search.maxThreads=8 \
    -e biu.search.loadCacheFirst=true \
    -e biu.search.maxCacheSizeMiB=512 \
    -e biu.download.mode="dl-single" \
    -e biu.download.aria2Host="localhost:6800" \
    -e biu.download.aria2Secret="******" \
    -e biu.download.deterPaths=true \
    -e biu.download.maxDownloading=8 \
    -e biu.download.saveURI="{ROOTPATH}/downloads/{date_today}/" \
    -e biu.download.saveFileName="{title}_{work_id}" \
    -e biu.download.autoArchive=true \
    -e biu.download.whatsUgoira=webp \
    -e biu.download.imageHost="" \
    -e secret.key.apiSauceNAO="***********************" \
    -v /mnt/user/Unraid/Download/Pixiv/downloads \
    -v /mnt/user/appdata/Pixiv/usr/.token \
    registry.cn-hangzhou.aliyuncs.com/zzcabc/pixivbiu:latest
    
    token是從主電腦成功跑上的PixivBiu直接提取檔案到/mnt/user/appdata/Pixiv/usr/.token \
    
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/dcc2fcf7-efc8-4f5d-acca-7c2a5a8c0f4e)
好像讀不到token

**Comment by SA8620** [comment]
這次我嘗試了以這種方式安裝：
`
docker run -d \
    --name pixivbiu \
    --user $(id -u):$(id -g) \
    -p 4001:80 \
    -e sys.debug=false \
    -e sys.apiRoute="direct" \
    -e sys.proxy="" \
    -e sys.language="" \
    -e sys.theme="multiverse" \
    -e biu.search.maxThreads=8 \
    -e biu.search.loadCacheFirst=true \
    -e biu.search.maxCacheSizeMiB=512 \
    -e biu.download.mode="aria2" \
    -e biu.download.aria2Host="localhost:6800" \
    -e biu.download.aria2Secret="*******" \
    -e biu.download.deterPaths=true \
    -e biu.download.maxDownloading=8 \
    -e biu.download.saveURI="{ROOTPATH}/downloads/{date_today}/" \
    -e biu.download.saveFileName="{title}_{work_id}" \
    -e biu.download.autoArchive=true \
    -e biu.download.whatsUgoira=webp \
    -e biu.download.imageHost="" \
    -e secret.key.apiSauceNAO="******" \
    -v /mnt/user/Unraid/Download/Pixiv/downloads \
    -v /mnt/user/appdata/Pixiv/usr/.token \
    registry.cn-hangzhou.aliyuncs.com/zzcabc/pixivbiu:latest
`
![圖片](https://github.com/txperl/PixivBiu/assets/112755150/ae5490b2-d20c-4ea2-be78-43c30be2ad46)

**Comment by txperl** [comment]
对，`.token` 里的内容不是 Code，而是你后来在电脑上使用 PixivBiu 登陆成功后生成的，你后面的操作应该是对的。

但你启动的参数错了，其中两个 `-v` 相关参数应该写成这样。

```
-v /mnt/user/Unraid/Download/Pixiv/downloads:/Pixiv/downloads
-v /mnt/user/appdata/Pixiv/usr/.token:/Pixiv/usr/.token
```

**Comment by txperl** [comment]
从报错来看，应该不是 Token 错误了，是网络问题。

如果 Docker 下实在没法启动，可以试着下个 PixivBiu Ubuntu 的编译包，应该也能直接跑，和电脑上一样。

**Comment by SA8620** [comment]
好的謝謝你，這樣我需要開虛擬機，有點麻煩和浪費資源。我去問問看Docker版本的作者吧。看過那邊好像也有這個問題，打擾了。至少目前在主機可以色色
謝謝你

**Comment by txperl** [comment]
哈哈哈不客气。
