### ISSUE TITLE
获取token后登录失败

### ISSUE THREAD

**Issue by lzlclzyx** [txperl/PixivBiu#7]
无意中发现这个软件，看介绍感觉不错，但是在使用中遇到一些问题。

一个是用了两种方法架了梯子，在浏览器中都是可以正常访问pixiv的。
但是打开软件却显示网络不行，无法访问pixiv

还有按照软件提示选择手动获取token，监听地址留空，获取到如下token
xxD*****k_w******p_uB***x0
中间部分用*代替。

输入后显示
Error:
        [ERROR] auth() failed! check username and password.
        HTTP 400: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
End;
Error:
        HTTPSConnectionPool(host='oauth.secure.pixiv.net', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
End;
[PixivBiu] Pixiv 登陆失败

请问是我获取的token不对吗？
还是其他哪个步骤有问题？

谢谢

**Comment by txperl** [comment]
因为 Pixiv 官方最近禁用了从前的 API 登录方式，所以目前只能通过 Token 登陆。

在获得 Code 后，程序会请求 Pixiv API 获取你的 Refresh Token。所以请确保程序可以访问 Pixiv：如果你在墙外，那无需额外配置；如果不在，那请务必正确使用代理并在程序中正确填写代理监听地址。

**Comment by txperl** [comment]
已经更新了新版本（v2.0.2），拿到 Code 后不需要代理即可获取 Token。

可以试一下，看看能不能解决你的问题？
