### ISSUE TITLE
根据指引登录后得到空白页面，无法得到token

### ISSUE THREAD

**Issue by C-INIT** [txperl/PixivBiu#72]
v2rayN全局代理，代理端口与PixivBiu检测结果一致，浏览器可正常浏览Pixiv。
但根据Login操作指引，在最新版的Chrome浏览器中输入网址：
https://app-api.pixiv.net/web/v1/login?code_challenge=fkl9zNJ62FO04rphZT3tPsTzV6WDeOrPxSYpecipunU&code_challenge_method=S256&client=pixiv-android
登录后得到如下空白页面：
![image](https://github.com/user-attachments/assets/be583b4d-538e-4fb9-8216-9754fbf00031)
图片中控制台输出的唯一报错信息如下：
Failed to launch 'pixiv://account/login?code=is6SaY3_o2ytPF8NQ6P05RNjwfJRSGe6mIkQR0e_t2g&via=login' because the scheme does not have a registered handler.

**Comment by txperl** [comment]
这样就是登录成功了。

你要把右边的【开发者工具 / DevTools】切换到【网络 / Network】标签页那边，然后照着 PixivBiu 的程序提示，就能拿到 Code 内容了。

**Comment by C-INIT** [comment]
已解决，感谢。

**Comment by txperl** [comment]
> 呃现在按照提示筛选"callback?"没显示一条地址，找不到`code`参数

可以先确认一下，在开发者工具那里有没有打开“日志「Preserve log / 持续记录」”选项。
