### ISSUE TITLE
排序失效

### ISSUE THREAD

**Issue by JasonxlxCharles** [txperl/PixivBiu#73]
选择排序模式的功能已经失效

试过多个选项，0、1、2全部失效，选择完没有变化，仍然是默认日期排序。

版本为最新2.6.3a

旧版本该功能曾经有效，新版本已经失效

**Comment by txperl** [comment]
请问是在排行榜页还是搜索页失效呢？如果是排行榜的话，需要在数字后加 s 才可以排序，比如 `0s`。
