### ISSUE TITLE
在手动获取token登录过程中出现若干错误

### ISSUE THREAD

**Issue by 2455DD** [txperl/PixivBiu#8]
您好，我在使用Release2.0.1_win版本的过程中，发现手动获取token登录过程中出现错误:
1、在第一次获得code并输入后程序重新进入手动获取token的开始
2、在第二次获得code并输入后程序报错，log如下:
Error:
        requests POST https://oauth.secure.pixiv.net/auth/token error: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.
End;
Error:
        request error
End;
请问这样的问题是出于怎样的原因，怎样的措施可以避免这一情景的再度发生，谢谢

**Comment by cnqdztp** [comment]
我也遇到了相同的问题，完全一致的流程，第一次获得code之后再次进入获取token的流程
然后退出程序，重新进入，获取code之后提示检测到captcha

**Comment by txperl** [comment]
抱歉，我没有遇到过这种情况，暂时也不能给出确切的解决方案...

这个问题应该是，第一次获取 Token 成功后尝试登陆，结果提示需要进行 CF CAPTCHA 验证，导致登陆失败从而程序进行第二次 Token 获取；因为请求获取 Token 与登陆所用的 API 是一个域，所以再次遇到验证要求，导致请求失败。

可以做以下尝试：
- 更换 Pixiv 账号
- 更换代理服务器
- 修改 `config.yml` 中 `sys-api` 一项，强制启用 `byPassSni` 模式

尝试后请务必告知结果，感谢。

**Comment by 2455DD** [comment]
> 抱歉，我没有遇到过这种情况，暂时也不能给出确切的解决方案...
> 
> 这个问题应该是，第一次获取 Token 成功后尝试登陆，结果提示需要进行 CF CAPTCHA 验证，导致登陆失败从而程序进行第二次 Token 获取；因为请求获取 Token 与登陆所用的 API 是一个域，所以再次遇到验证要求，导致请求失败。
> 
> 可以做以下尝试：
> 
> * 更换 Pixiv 账号
> * 更换代理服务器
> * 修改 `config.yml` 中 `sys-api` 一项，强制启用 `byPassSni` 模式
> 
> 尝试后请务必告知结果，感谢。

您好，今天在更换了代理服务器并使用了Nginx反代后就可以正常的使用了，十分感谢您的协助。
