### ISSUE TITLE
[PixivBiu] Pixiv 登陆失败

### ISSUE THREAD

**Issue by YuMXuan** [txperl/PixivBiu#9]
输入code之后不能登录。

`Error:
HTTPSConnectionPool(host='210.140.131.199', port=443): Max retries exceeded with url: /auth/token (Caused by SSLError(SSLCertVerificationError("hostname '210.140.131.199' doesn't match either of '*.pixiv.net', 'pixiv.me', 'public-api.secure.pixiv.net', 'oauth.secure.pixiv.net', 'www.pixivision.net', 'fanbox.cc', '*.fanbox.cc', 'pixiv.net'")))
End;
[PixivBiu] 免代理请求失败。开始尝试代理方式，请务必确保程序可通过您的设置访问 Pixiv
[Login] 获取到值为 http://127.0.0.1:7890/ 的代理监听地址，是否需要修改? (y / n): n
Error:
[ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
End;
Error:
Request Error.
Response: {'has_error': True, 'errors': {'system': {'message': '不正なリクエストです。', 'code': 918}}, 'error': 'invalid_request'}
End;
[PixivBiu] Pixiv 登陆失败`

**Comment by YuMXuan** [comment]
使用的版本是：PixivBiu_2.0.2_mac_intel

**Comment by txperl** [comment]
「不正なリクエストです。」错误一般是因为 Code 输入错误导致。

程序每次启动时要求获取的 Code 都不同，不可复用之前获取到的。Code 不带有任何引号或等号，除此之外请按照程序步骤来操作，一般是不会有错的。

可以再试一下看看？

**Comment by YuMXuan** [comment]
多次尝试之后成功了！谢谢！
